version: '3'
services:
  calculator:
    build: ./calculator
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - shared_network
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - shared_network
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - shared_network
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - shared_network
  gateway:
    build: ./gateway
    ports:
      - 8000:8000
    networks:
      - shared_network
  rabbitmq:
    image: "rabbitmq:3.13-rc-management"
    container_name: rabbitmq_container
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    networks:
      - shared_network

networks:
  shared_network:
    external: true