version: '3'
services:
  web:
    build: ./calculator
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
