# Docker Compose file for the our systems loan services
# Both registries and providers are built for each loan type

version: '3'

services:
# Eureka server for service discovery
  eureka-server:
    image: rodolfoalvarenga/eureka-server
    ports:
      - "8761:8761"
    networks:
      - shared_network
  
# Student loan services
  student-loan-registry:
    build: ./student-loan/student-loan-registry
    depends_on:
      - eureka-server
    networks:
      - shared_network
  student-loan-aib:
    build: ./student-loan/student-loan-aib
    depends_on:
      - student-loan-registry
      - eureka-server
    networks:
      - shared_network
  student-loan-credit-union:
    build: ./student-loan/student-loan-credit-union
    depends_on:
      - student-loan-registry
      - eureka-server
    networks:
      - shared_network
  student-loan-vendor-finance:
    build: ./student-loan/student-loan-vendor-finance
    depends_on:
      - student-loan-registry
      - eureka-server
    networks:
      - shared_network
  student-loan-boi:
    build: ./student-loan/student-loan-boi
    depends_on:
      - student-loan-registry
      - eureka-server
    networks:
      - shared_network

# Personal loan services
  personal-loan-registry:
    build: ./personal-loan/personal-loan-registry
    depends_on:
      - eureka-server
    networks:
      - shared_network
  personal-loan-aib:
    build: ./personal-loan/personal-loan-aib
    depends_on:
      - personal-loan-registry
      - eureka-server
    networks:
      - shared_network
  personal-loan-avant-money:
    build: ./personal-loan/personal-loan-avant-money
    depends_on:
      - personal-loan-registry
      - eureka-server
    networks:
      - shared_network
  personal-loan-an-post:
    build: ./personal-loan/personal-loan-an-post
    depends_on:
      - personal-loan-registry
      - eureka-server
    networks:
      - shared_network
  personal-loan-kbc-bank:
    build: ./personal-loan/personal-loan-kbc-bank
    depends_on:
      - personal-loan-registry
      - eureka-server
    networks:
      - shared_network

# Home loan services
  home-loan-registry:
    build: ./home-loan/home-loan-registry
    depends_on:
      - eureka-server
    networks:
      - shared_network
  home-loan-aib:
    build: ./home-loan/home-loan-aib
    depends_on:
      - home-loan-registry
      - eureka-server
    networks:
      - shared_network
  home-loan-ptsb:
    build: ./home-loan/home-loan-ptsb
    depends_on:
      - home-loan-registry
      - eureka-server
    networks:
      - shared_network
  home-loan-boi:
    build: ./home-loan/home-loan-boi
    depends_on:
      - home-loan-registry
      - eureka-server
    networks:
      - shared_network
  home-loan-kbc-bank:
    build: ./home-loan/home-loan-kbc-bank
    depends_on:
      - home-loan-registry
      - eureka-server
    networks:
      - shared_network

# Car loan service
  car-loan-registry:
    build: ./car-loan/car-loan-registry
    depends_on:
      - eureka-server
    networks:
      - shared_network
  car-loan-aib:
    build: ./car-loan/car-loan-aib
    depends_on:
      - car-loan-registry
      - eureka-server
    networks:
      - shared_network
  car-loan-avant-money:
    build: ./car-loan/car-loan-avant-money
    depends_on:
      - car-loan-registry
      - eureka-server
    networks:
      - shared_network
  car-loan-vendor-finance:
    build: ./car-loan/car-loan-vendor-finance
    depends_on:
      - car-loan-registry
      - eureka-server
    networks:
      - shared_network
  car-loan-kbc-bank:
    build: ./car-loan/car-loan-kbc-bank
    depends_on:
      - car-loan-registry
      - eureka-server
    networks:
      - shared_network

# Network for system (Note: make sure to create this manually (see readme))
networks:
  shared_network:
    external: true